import {useState} from 'react';
import {useLang} from '@/context/LangContext';
import api from '@/lib/api';
export default function WithdrawalForm(){
 const {lang}=useLang();const hu=lang==='hu';const [data,setData]=useState({full_name:'',email:'',contract:'',message:''});const [busy,setBusy]=useState(false);const [receipt,setReceipt]=useState(null);const [error,setError]=useState(false);
 const submit=async e=>{e.preventDefault();setBusy(true);setError(false);try{const r=await api.post('/withdrawals',{...data,confirmed:true,lang});setReceipt(r.data);}catch{setError(true);}finally{setBusy(false);}};
 return <section id="elallas-urlap" className="mt-12 p-6 border border-[#D4AF6E]/40"><h2 className="font-serif-display text-3xl mb-5">{hu?'Elállás a szerződéstől':'Withdraw from the contract'}</h2>{receipt?<div role="status"><p>{hu?'Elállási nyilatkozatodat rögzítettük. E-mailes átvételi elismervényt küldünk.':'Your withdrawal notice has been recorded. An acknowledgement will be emailed to you.'}</p><p className="my-3 break-all">{receipt.reference} · {receipt.received_at}</p><pre className="whitespace-pre-wrap text-sm">{receipt.statement}</pre><button className="btn-outline mt-4" onClick={()=>{const url=URL.createObjectURL(new Blob([receipt.reference+'\n'+receipt.received_at+'\n'+receipt.statement],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='elallasi-nyilatkozat.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}>{hu?'Elismervény mentése':'Save acknowledgement'}</button></div>:<form onSubmit={submit} className="space-y-4">
 <p className="text-[#B8AE95]">{hu?'Kijelentem, hogy elállok az alább azonosított szerződéstől, a megjelölt termékek tekintetében. Indoklás nem szükséges.':'I withdraw from the contract identified below in respect of the specified goods. No reason is required.'}</p>
 {[['full_name',hu?'Teljes név':'Full name',250],['email',hu?'E-mail az elismervényhez':'Email for acknowledgement',254],['contract',hu?'Rendelésazonosító vagy a szerződés azonosító adatai':'Order reference or details identifying the contract',500],['message',hu?'Érintett termékek (üresen: a teljes rendelés)':'Goods concerned (blank: entire order)',2000]].map(([key,label,max])=><label className="block text-sm" key={key}>{label}<input type={key==='email'?'email':'text'} required={key!=='message'} maxLength={max} value={data[key]} onChange={e=>setData({...data,[key]:e.target.value})} className="block w-full bg-[#24221E] border border-[#3d3835] p-3 mt-2 focus-ring"/></label>)}
 {error&&<p role="alert">{hu?'A beküldés nem sikerült. Próbáld újra, vagy írj a hinfinicandles@hinfinicandles.hu címre.':'Submission failed. Try again or email hinfinicandles@hinfinicandles.hu.'}</p>}
 <button disabled={busy} className="btn-primary focus-ring">{busy?(hu?'Küldés…':'Submitting…'):(hu?'Elállás megerősítése':'Confirm withdrawal')}</button></form>}</section>;
}
