import { useEffect, useState } from 'react';
import { toast } from 'sonner';
import api from '@/lib/api';
import { getToken } from '@/admin/adminApi';
import { formatPrice } from '@/context/LangContext';
const auth=()=>({headers:{'X-Admin-Token':getToken()}});
const msg=e=>e.response?.data?.detail||'A művelet nem sikerült.';
const call=(method,path,data)=>api({method,url:'/admin/'+path,data,...auth()});
const dateInput=v=>{if(!v)return '';const d=new Date(v);return new Date(d-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
const utc=v=>v?new Date(v).toISOString():'';
function Field({label,children}){return <label className="block space-y-2"><span className="block text-sm">{label}</span>{children}</label>;}
export default function AdminStudio({mode}){
 const [items,setItems]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[form,setForm]=useState(null),[selected,setSelected]=useState(null);
 const path=mode==='custom'?'custom-requests':mode;
 const load=()=>call('GET',path).then(r=>{if(mode==='studio')setForm(r.data);else setItems(r.data);setError('');}).catch(e=>setError(msg(e)));
 useEffect(()=>{setForm(null);setSelected(null);load();},[mode]); // Each tab loads its own resource.
 const act=async fn=>{setBusy(true);try{await fn();toast.success('Mentve.');await load();return true;}catch(e){toast.error(msg(e));return false;}finally{setBusy(false);}};
 const field=(k,label,type='text')=><Field label={label}><input className="admin-input" type={type} required={!['starts_at','ends_at'].includes(k)} min={type==='number'?0:undefined} value={form[k]??''} onChange={e=>setForm({...form,[k]:type==='number'?Number(e.target.value):e.target.value})}/></Field>;
 const download=async r=>{try{const {data}=await api.get('/admin/custom-requests/'+r.request_id+'/image',{...auth(),responseType:'blob'});const u=URL.createObjectURL(data);const a=document.createElement('a');a.href=u;a.download='gyertyaterv.'+(r.attachment?.file?.split('.').pop()||'png');a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}catch{toast.error('A kép nem tölthető le.');}};
 const states={NEW:'Új ajánlatkérés',QUOTED:'Ajánlat elküldésre vár / elküldve',PAID:'Átutalás beérkezett',CLOSED:'Lezárva'};
 return <div className="space-y-6">{error&&<p role="alert" className="text-red-300">{error}</p>}
 {mode==='studio'&&form&&<form className="admin-card p-6 space-y-5 max-w-2xl" onSubmit={e=>{e.preventDefault();act(()=>call('PUT','studio',form));}}><h2 className="text-2xl font-serif-display">Választható lehetőségek</h2><p>Minden sorba egy lehetőséget írj. Csak valóban vállalható illatot, tartót és színt adj meg.</p>{[['scents','Illatok'],['containers','Tartók'],['colors','Szövegszínek']].map(([k,l])=><Field key={k} label={l}><textarea rows={5} className="admin-input" value={form[k].join('\n')} onChange={e=>setForm({...form,[k]:e.target.value.split('\n')})}/></Field>)}<button disabled={busy} className="btn-primary">Mentés</button></form>}
 {mode==='custom'&&<><p className="text-[#B8AE95]">Az ajánlat e-mailben, kizárólag átutalásos fizetési adatokkal megy ki. A levelek küldési állapotát az E-mail naplóban ellenőrizheted.</p>{items.length===0&&<p>Még nem érkezett egyedi ajánlatkérés.</p>}{items.map(r=><article key={r.request_id} className="admin-card p-6 space-y-3"><h2 className="text-2xl font-serif-display">{r.full_name}</h2><p>{r.email} · {r.phone} · {states[r.status]}</p><p className="text-sm break-all">{r.request_id} · {new Date(r.created_at).toLocaleString('hu-HU')}</p><p>Illat: {r.scent} · Tartó: {r.container}</p><p className="whitespace-pre-wrap">Felirat: {r.text||'—'} · Szín: {r.color||'—'}</p><p className="whitespace-pre-wrap">Elképzelés: {r.idea||'—'}</p>{r.attachment&&<button className="btn-outline" onClick={()=>download(r)}>Vásárlói kép letöltése</button>}{r.quote&&<div className="border-t border-[#3d3835] pt-4"><p>Legutóbbi ajánlat: {formatPrice(r.quote.amount)}</p><p className="whitespace-pre-wrap">{r.quote.message}</p></div>}<div className="flex flex-wrap gap-3">{['NEW','QUOTED'].includes(r.status)&&<button className="btn-primary" onClick={()=>{setSelected(r.request_id);setForm({amount:r.quote?.amount||0,message:r.quote?.message||''});}}>Ajánlat összeállítása</button>}{r.status==='QUOTED'&&<button disabled={busy} className="btn-outline" onClick={()=>{if(window.confirm('Ellenőrizted a bankszámlán, hogy az összeg valóban beérkezett?'))act(()=>call('PATCH','custom-requests/'+r.request_id,{status:'PAID'}));}}>Átutalás beérkezett</button>}{r.status!=='CLOSED'&&<button disabled={busy} className="btn-outline" onClick={()=>{if(window.confirm('Lezárod az ajánlatkérést?'))act(()=>call('PATCH','custom-requests/'+r.request_id,{status:'CLOSED'}));}}>Lezárás</button>}</div>
 {selected===r.request_id&&form&&<form className="border-t border-[#3d3835] pt-5 space-y-4" onSubmit={async e=>{e.preventDefault();if(window.confirm('Elküldöd ezt az ajánlatot a vásárlónak e-mailben?')&&await act(()=>call('POST','custom-requests/'+r.request_id+'/quote',form))){setSelected(null);setForm(null);}}}>{field('amount','Teljes fizetendő összeg, szállítással együtt (Ft)','number')}<Field label="Ajánlat részletei: tartalom, elkészítési idő, szállítás, érvényesség"><textarea required rows={6} className="admin-input" value={form.message} onChange={e=>setForm({...form,message:e.target.value})}/></Field><p>A bankszámlaadatokat és az ajánlatkérés azonosítóját a levél automatikusan hozzáadja.</p><button disabled={busy} className="btn-primary">Ajánlat küldése e-mailben</button></form>}</article>)}</>}
 {['coupons','events'].includes(mode)&&<><button className="btn-primary" onClick={()=>{setSelected(null);setForm(mode==='coupons'?{code:'',type:'percent',value:10,minimum:0,limit:0,starts_at:'',ends_at:'',active:true}:{title:'',location:'',description:'',starts_at:'',active:true});}}>{mode==='coupons'?'Új kupon':'Új esemény'}</button>
 {form&&<form className="admin-card p-6 space-y-4 max-w-3xl" onSubmit={async e=>{e.preventDefault();const body={...form,starts_at:utc(form.starts_at),...(mode==='coupons'?{ends_at:utc(form.ends_at)}:{})};if(await act(()=>call(selected?'PUT':'POST',path+(selected?'/'+encodeURIComponent(selected):''),body)))setForm(null);}}>
 {mode==='coupons'?<><Field label="Kuponkód (mentés után nem módosítható)"><input required disabled={!!selected} pattern="[A-Za-z0-9_-]{3,40}" className="admin-input" value={form.code} onChange={e=>setForm({...form,code:e.target.value.toUpperCase()})}/></Field><Field label="Kedvezmény típusa"><select className="admin-input" value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="percent">Százalék</option><option value="fixed">Fix összeg (Ft)</option></select></Field>{field('value',form.type==='percent'?'Kedvezmény (%)':'Kedvezmény (Ft)','number')}{field('minimum','Minimum termékérték (Ft)','number')}{field('limit','Összes felhasználás felső határa (0 = korlátlan)','number')}<p className="text-sm">A kedvezmény a termékekre vonatkozik. Egy rendeléshez egy kupon használható. A szállítási díjat a kedvezmény előtti termékérték határozza meg.</p></>:<>{field('title','Esemény neve')}{field('location','Helyszín')}<Field label="Leírás"><textarea className="admin-input" rows={5} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></Field></>}
 {field('starts_at',mode==='coupons'?'Érvényesség kezdete (elhagyható)':'Esemény időpontja','datetime-local')}{mode==='coupons'&&field('ends_at','Lejárat (elhagyható)','datetime-local')}<p className="text-sm">Az időpontot a böngésződ helyi időzónája szerint adod meg.</p><label className="flex gap-3"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/>{mode==='coupons'?'Kupon aktív':'Esemény nyilvános'}</label><div className="flex gap-3"><button disabled={busy} className="btn-primary">Mentés</button><button type="button" className="btn-outline" onClick={()=>setForm(null)}>Mégse</button></div></form>}
 {items.length===0&&<p>Még nincs rögzített {mode==='coupons'?'kupon':'esemény'}.</p>}{items.map(r=><div key={r.code||r.event_id} className="admin-card p-5 flex flex-wrap justify-between gap-4"><div><strong>{r.code||r.title}</strong><p>{r.active?'Aktív':'Inaktív'}{mode==='coupons'?` · ${r.value}${r.type==='percent'?'%':' Ft'} · Felhasználva: ${r.used}${r.limit?'/'+r.limit:''}`:` · ${new Date(r.starts_at).toLocaleString('hu-HU')} · ${r.location}`}</p></div><button className="btn-outline" onClick={()=>{setSelected(r.code||r.event_id);setForm({...r,starts_at:dateInput(r.starts_at),ends_at:dateInput(r.ends_at)});}}>Szerkesztés</button></div>)}</>}
 </div>;
}
