import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import api from "@/lib/api";
import Seo from "@/components/Seo";
import { useLang } from "@/context/LangContext";
const cls="admin-input !py-3";
function Page({title,children}) {return <div className="max-w-4xl mx-auto px-6 py-16"><Seo title={title}/><h1 className="font-serif-display text-4xl sm:text-5xl mb-8">{title}</h1>{children}</div>;}
export function About(){const {t}=useLang();return <Page title={t('nav.about')}><img src="/hinfini-logo.png" alt="H’INFINI Candles" className="w-48 h-48 rounded-full mx-auto mb-8"/><div className="space-y-6 text-lg text-[#B8AE95] leading-relaxed"><p>{t('brand.p1')}</p><p>{t('brand.p2')}</p><Link className="btn-primary" to="/egyedi-gyertyak">{t('nav.custom')}</Link></div></Page>;}
export function Events(){const [items,setItems]=useState(null);const [error,setError]=useState(false);useEffect(()=>{api.get('/events').then(r=>setItems(r.data)).catch(()=>setError(true));},[]);return <Page title="Események">{error?<p>Az események most nem tölthetők be. Frissítsd az oldalt.</p>:items===null?<p>Betöltés…</p>:items.length===0?<p className="text-[#B8AE95]">Jelenleg nincs meghirdetett eseményünk. Nézz vissza később!</p>:<div className="space-y-6">{items.map(e=><article key={e.event_id} className="admin-card p-6"><h2 className="font-serif-display text-3xl">{e.title}</h2><p className="text-[#D4AF6E] my-3">{new Date(e.starts_at).toLocaleString('hu-HU',{timeZone:'Europe/Budapest'})} · {e.location}</p><p className="whitespace-pre-wrap">{e.description}</p></article>)}</div>}</Page>;}
export function CustomCandles(){
 const [options,setOptions]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[sent,setSent]=useState(null),[image,setImage]=useState(null),[focused,setFocused]=useState(false);
 const [form,setForm]=useState({full_name:'',email:'',phone:'',scent:'',container:'',text:'',color:'',idea:'',website:'',consent:false});
 useEffect(()=>{api.get('/studio').then(r=>setOptions(r.data)).catch(()=>setError('A lehetőségek nem tölthetők be. Frissítsd az oldalt.'));},[]);
 const change=k=>e=>setForm({...form,[k]:e.target.type==='checkbox'?e.target.checked:e.target.value});
 const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{const data=new FormData();Object.entries(form).forEach(([k,v])=>data.append(k,k==='consent'?(v?'1':'0'):v));if(image)data.append('image',image);const r=await api.post('/custom-requests',data);setSent(r.data);}catch(e){setError(e.response?.data?.detail||'Az elküldés nem sikerült. Próbáld újra.');}finally{setBusy(false);}};
 return <Page title="Egyedi gyertyák">{sent?<div role="status" className="admin-card p-8"><h2 className="text-2xl mb-4">Köszönjük az ajánlatkérést!</h2><p>{sent.message}</p><p className="mt-4 text-sm break-all">Azonosító: {sent.request_id}</p></div>:<><p className="text-lg text-[#B8AE95] mb-8">Mondd el, milyen gyertyát szeretnél! Személyre szabott ajánlatot küldünk e-mailben. Elfogadás után kizárólag átutalással fizethetsz; az ajánlatkérés még nem jár fizetési kötelezettséggel.</p>{error&&<p role="alert" className="mb-6 text-red-300">{error}</p>}{options&&<form onSubmit={submit} className="space-y-6">
 <div className="grid sm:grid-cols-2 gap-6">{[['full_name','Név','text'],['email','E-mail-cím','email'],['phone','Telefonszám (nem kötelező)','tel']].map(([k,l,type])=><label key={k} className="block">{l}<input className={cls} type={type} required={k!=='phone'} maxLength={250} value={form[k]} onChange={change(k)}/></label>)}</div>
 <div className="grid sm:grid-cols-2 gap-6">{[['scent','Illat','scents'],['container','Tartó','containers']].map(([k,l,o])=><label key={k}>{l}<select required className={cls} value={form[k]} onChange={change(k)}><option value="">Válassz…</option>{options[o].map(v=><option key={v}>{v}</option>)}</select></label>)}</div>
 <label className="block">A gyertyára kért szöveg<textarea rows={3} maxLength={1000} className={cls} value={form.text} onChange={change('text')}/></label>
 <label className="block">Kép feltöltése (nem kötelező)<input type="file" accept="image/jpeg,image/png,image/webp" className="block mt-3 w-full" onChange={e=>{const f=e.target.files[0];if(f&&f.size>5*1024*1024){setError('A kép legfeljebb 5 MB lehet.');e.target.value='';setImage(null);}else{setImage(f||null);setError('');}}}/><span className="text-sm text-[#B8AE95]">JPG, PNG vagy WebP; legfeljebb 5 MB. A képet csak mi látjuk az ajánlatkéréshez.</span></label>
 {!image&&<label className="block">Szöveg színe<select required={!!form.text} className={cls} value={form.color} onChange={change('color')}><option value="">Válassz…</option>{options.colors.map(v=><option key={v}>{v}</option>)}</select></label>}
 <label className="block">Egyedi elképzelés<textarea rows={5} maxLength={5000} className={cls} value={form.idea} onChange={change('idea')} placeholder={focused?'':'Halloween stílusú, kicsi tök fejekkel'} onFocus={()=>setFocused(true)} onBlur={()=>setFocused(false)}/></label>
 <div hidden aria-hidden="true"><input tabIndex={-1} autoComplete="off" value={form.website} onChange={change('website')}/></div>
 <label className="flex gap-3"><input type="checkbox" required checked={form.consent} onChange={change('consent')}/><span>Hozzájárulok az ajánlatkéréshez megadott adataim és képem kezeléséhez az <Link to="/adatkezeles" target="_blank" className="underline">adatkezelési tájékoztató</Link> szerint.</span></label>
 <button className="btn-primary" disabled={busy}>{busy?'Küldés…':'Ajánlatot kérek'}</button></form>}</>}</Page>;
}
