const labels = {
  "Piros": "Red",
  "Fehér": "White",
  "Barna": "Brown",
  "Rózsaszín": "Pink",
  "Sötétlila": "Dark purple",
  "Világoslila": "Light purple",
  "Sötétkék": "Dark blue",
  "Világoskék": "Light blue",
  "Citromsárga": "Yellow",
  "Narancssárga": "Orange",
  "Fekete": "Black",
  "Arany": "Gold",
  "Egyeztetést kérek": "I would like to discuss the options",
  "gyertya": "candle",
  "db": "pcs",
  "Sütőtök erdő": "Pumpkin Forest",
  "kb. 70 g": "approx. 70 g",
  "Áfonyás joghurttorta": "Blueberry Yogurt Cake",
  "kb. 70 g + viaszdekoráció": "approx. 70 g + wax decoration",
  "Ölelő nyuszi": "Hugging Bunny",
  "kb. 50 g": "approx. 50 g",
  "Te vagy a legjobb Apa!": "You’re the Best Dad!",
  "kb. 130 g": "approx. 130 g",
  "Púderfülű nyuszi": "Powder-Eared Bunny",
  "kb. 70–80 g": "approx. 70–80 g",
  "Az otthon illata": "The Scent of Home",
  "kb. 30 g": "approx. 30 g",
  "Málnás panna cotta": "Raspberry Panna Cotta",
  "kb. 90g": "approx. 90g",
  "Szicíliai citrom & mentol illatviasz": "Sicilian Lemon & Menthol Wax Melts",
  "kb. 25 g": "approx. 25 g",
  "Tulipáncsokor": "Tulip Bouquet",
  "kb. 150 g": "approx. 150 g",
  "Levendula & rózsa illatviasz": "Lavender & Rose Wax Melts",
  "Epres érintés illatviasz": "Strawberry Touch Wax Melts",
  "Toszkán naplemente": "Tuscan Sunset",
  "70 g": "70 g",
  "Pumpkin Spice illatviasz": "Pumpkin Spice Wax Melts",
  "kb. 40 g": "approx. 40 g",
  "Rózsával borított maci gyertya": "Rose-Covered Teddy Bear Candle",
  "Elvarázsolt üst": "Enchanted Cauldron",
  "kb. 90 g": "approx. 90 g",
  "Virágos maci gyertya": "Floral Teddy Bear Candle",
  "Sült alma & vörösáfonya": "Baked Apple & Cranberry",
  "Madagaszkári vanília illatviasz": "Madagascan Vanilla Wax Melts",
  "30 g": "30 g",
  "Te vagy a legjobb Anya!": "You’re the Best Mum!",
  "tegelyes-gyertyak-4oz": "Container candles – 4 oz",
  "Tégelyes gyertyák – 4 oz": "Container candles – 4 oz",
  "tegelyes-gyertyak-8oz": "Container candles – 8 oz",
  "Tégelyes gyertyák – 8 oz": "Container candles – 8 oz",
  "forma-gyertyak": "Shaped candles",
  "Formagyertyák": "Shaped candles",
  "uveges-gyertyak": "Glass jar candles",
  "Üveges gyertyák": "Glass jar candles",
  "illatviasz": "Wax melts",
  "Illatviasz": "Wax melts"
};
export const english = value => labels[value] || value || "";
