const HU_CONTENT = {
  "Candles": "Gyertyák",
  "Wax": "Viaszok",
  "Fragrance Oils": "Illatolajok",
  "Essential Oils": "Illóolajok",
  "Wicks": "Kanócok",
  "Containers": "Edények",
  "Tools": "Eszközök",
  "Kits": "Kezdőcsomagok",
  "Container": "Edényes gyertya",
  "Taper": "Szálgyertya",
  "Pillar": "Tömbgyertya",
  "Gel": "Gélgyertya",
  "Soy": "Szója",
  "Beeswax": "Méhviasz",
  "Coconut": "Kókusz",
  "Paraffin": "Paraffin",
  "Cotton": "Pamut",
  "Wood": "Fa",
  "Hemp": "Kender",
  "Floral": "Virágos",
  "Woody": "Fás",
  "Fresh": "Friss",
  "Citrus": "Citrusos",
  "Glass": "Üveg",
  "Ceramic": "Kerámia",
  "Metal": "Fém",
  "Beginner": "Kezdő",
  "Advanced": "Haladó",
  "amber": "borostyán",
  "beeswax": "méhviasz",
  "blend": "keverék",
  "cedarwood": "cédrusfa",
  "ceramic": "kerámia",
  "coconut": "kókusz",
  "container": "edényes",
  "cotton": "pamut",
  "eucalyptus": "eukaliptusz",
  "fig": "füge",
  "gel": "gél",
  "green": "zöld",
  "hemp": "kender",
  "kit": "kezdőcsomag",
  "lavender": "levendula",
  "orange": "narancs",
  "oud": "agarfa",
  "paraffin": "paraffin",
  "pillar": "tömbgyertya",
  "soy": "szója",
  "tobacco": "dohány",
  "tool": "eszköz",
  "vanilla": "vanília",
  "wax": "viasz",
  "wick": "kanóc",
  "wood": "fa",
  "checkout": "Pénztár",
  "footer": "Lábléc",
  "none": "Nincs beállítva",
  "local": "Helyi tárhely",
  "s3": "Felhőtárhely (S3/R2)",
  "Edényes Gyertya Módszer": "Edényes gyertya készítése",
  "Kézzel Mártott Méhviasz Gyertya": "Kézzel mártott méhviaszgyertya",
  "Öntött Pillér Gyertyák": "Öntött tömbgyertyák",
  "Illat & Illóolaj Keverés": "Illatolajok és illóolajok keverése",
  "Kanóc Méretezés": "Kanócméretezés",
  "Anyagok & Eszközök": "Anyagok és eszközök",
  "Gyertya Biztonság": "A gyertyakészítés és gyertyaégetés biztonsága",
  "Illat vs illóolaj": "Illatolaj és illóolaj: mi a különbség?",
  "Teszt égés": "Próbaégetés",
  "Illat mennyiség": "Az illatanyag mennyisége",
  "Edény hőmérséklet": "Az edény hőmérséklete",
  "Első égés szabály": "Az első égetés szabálya",
  "Forma előkészítés": "A forma előkészítése",
  "Blend": "Keverék",
  "Green": "Zöld",
  "Herbal": "Gyógynövényes",
  "Measurement": "Mérés",
  "Pouring": "Öntés",
  "Setup": "Előkészítés",
  "Smoky": "Füstös",
  "Traditional": "Hagyományos",
  "Trimming": "Kanócvágás",
  "Warm": "Meleg",
  "storage": "Képtárolás",
  "2.5 kg": "2,5 kg",
  "Cédrus & Vetiver Pillér": "Cédrus- és vetiverillatú tömbgyertya",
  "Paraffin Pillér Viasz": "Paraffinviasz tömbgyertyához",
  "Vanília Oud Illatolaj": "Vaníliás agarfaillatolaj",
  "Füge & Páfrány Illatolaj": "Füge- és páfrányillatolaj",
  "Gazdag, gyantás vanília sötét oud-dal.": "Gazdag, gyantás vanília agarfaillattal.",
  "Zöld füge levél, moha & lágy pézsma.": "Zöld fügelevél, moha és lágy pézsma.",
  "Rusztikus paraffin/szója pillér gyertya.": "Rusztikus paraffin- és szójaviasz tömbgyertya.",
  "order_created": "Rendelés-visszaigazolás",
  "payment_success": "Sikeres fizetés",
  "payment_failed": "Sikertelen fizetés",
  "shipped": "Csomag feladva",
  "cancelled": "Rendelés törölve",
  "admin_new_order": "Új rendelés – belső értesítés",
  "admin_paid": "Sikeres fizetés – belső értesítés",
  "admin_payment_failed": "Sikertelen fizetés – belső értesítés",
  "admin_cancel_request": "Rendelés törlése – belső értesítés",
  "admin_low_stock": "Alacsony készlet",
  "created": "Rendelés létrehozva",
  "additional_successful_payment": "További sikeres fizetés – ellenőrzés szükséges",
  "NEW": "Új",
  "AWAITING_PAYMENT": "Fizetésre vár",
  "PAID": "Fizetve",
  "PACKING": "Csomagolás alatt",
  "SHIPPED": "Feladva",
  "COMPLETED": "Teljesítve",
  "CANCELLED": "Törölve",
  "FINISHED": "Sikeres fizetés",
  "TIMEOUT": "Lejárt fizetés",
  "NOTAUTHORIZED": "Elutasított fizetés",
  "FAIL": "Sikertelen fizetés"
};

export const hungarian = (value) => HU_CONTENT[value] ?? value ?? "";

export function historyLabel(value, lang = "hu") {
  if (lang !== "hu") return value;
  if (value.startsWith("admin:")) return "Állapotmódosítás: " + value.slice(6).split("->").map(hungarian).join(" → ");
  if (value.startsWith("ipn:")) return "Fizetési értesítés: " + hungarian(value.slice(4));
  return hungarian(value);
}
